services:
  api:
    build: .
    env_file:
      - .env
    container_name: schedule_api_service
    restart: always
    command: ["make", "run_dev"]
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:8.0-alpine
    container_name: schedule_api_redis
    restart: unless-stopped
    command:
      - redis-server

  postgres:
    image: postgres:17-alpine
    container_name: schedule_api_db
    restart: unless-stopped
    env_file:
      .env
    ports:
      - "5432:5432"
    volumes:
      - "db_data:/var/lib/postgresql/data"


volumes:
  db_data:
